Liquid jet
pcdshub/pcdsdevices pull request #1053
Opened 2022-09-15 23:21 UTC by vespos

## Description
Add liquid_jet class for MFX and XCS liquid jet setups.

## Motivation and Context
Devices used regularly at MFX, XCS, and XPP.

## How Has This Been Tested?
Used at MFX to generate the screens based on the happi entry pointing to this class.

## Where Has This Been Documented?
Docstrings

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive docstrings, including context and API
- [ ] New/changed functions and methods are covered in the test suite where possible
- [ ] Test suite passes locally
- [ ] Test suite passes on travis
- [ ] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

2022-09-16 16:23 UTC, tangkong requested changes
The test suite failed on a test that's seemingly unrelated to this.  looking into it now, but in the meantime there's a couple quick style changes that'd be nice to get in.

2022-09-16 16:23 UTC, tangkong commented on pcdsdevices/liquid_jet.py
> +    #_icon = 'fa.minus-square'
```suggestion
    # _icon = 'fa.minus-square'
```
Style dictates we put a space after the comment '#'.  Did you want this to have an icon though?

2022-09-16 16:23 UTC, tangkong commented on pcdsdevices/liquid_jet.py
> +    #_icon = 'fa.clock-o'
```suggestion
    # _icon = 'fa.clock-o'
```
same as above.  Though if we have one we should delete the other

2022-09-19 22:46 UTC, ZLLentz commented
reference to the flaky test issue, must be unrelated to this PR: https://github.com/pcdshub/pcdsdevices/issues/1050

2022-09-19 22:58 UTC, ZLLentz commented
I think we can merge if you uncomment, remove, or fix the style thing on the lines that Robert pointed out above.

Currently this icon string is used in lightpath to pick an icon.

2022-09-22 04:34 UTC, vespos commented
Hi thanks both for your feedback. I actually realized that we already have a jet class (jet.py). I'd have to check that it works fine with the newer version of the jet that we have at MFX. Or we might consider updating the old XCS liquid jet to a newer version compatible with the current Beckhoff axis class.

2022-09-22 17:09 UTC, tangkong commented
Ah!  You're absolutely right.  It looks like the `pcdsdevices.jet.BeckhoffJet` class should reproduce what you've written in this PR, unless the `BeckhoffAxis_Pre140` is out of date.  A quick look through happi seems to suggest that there aren't any devices using `BeckhoffJet` right now, so updating the `BeckhoffAxis_Pre140` components could be an un-disruptive option.

2023-04-13 18:46 UTC, closed without merging