Adding base class for HxrDiffractometer
pcdshub/pcdsdevices pull request #1274
Opened 2024-08-20 16:41 UTC by c-tsoi

## Description

Adding base class for HxrDiffractometer, this class will ask the user to input the prefix HXR:GON:MMS: and it has the motion stages hardcoded.
## Motivation and Context

This change allows us to control the hxr diffractometer stages using python.
## How Has This Been Tested?

I was able to connect to the PVs and I have done motion test to the stages.
## Where Has This Been Documented?

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive docstrings, including context and API
- [ ] New/changed functions and methods are covered in the test suite where possible
- [ ] Test suite passes locally
- [ ] Test suite passes on GitHub Actions
- [ ] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

2024-08-23 21:26 UTC, tangkong commented
I think the lakeshore file was removed a while ago.  Your branch is a bit out of date, we should rebase or merge the master into this branch.  

Let me know if you need help with this

2024-08-26 18:24 UTC, ZLLentz commented
I think the lakeshore was never part of pcdsdevices, there's a super old issue to add one and I can't find any point in time where we completed the task (#826). The file is new to me at least. Probably these should be split into two PRs, or if that is prohibitive we can do a 2-in-1 with some updated documentation.

2024-08-26 19:18 UTC, tangkong commented
We sorted this out offline, Christian will be splitting this up into two PRs, and we rebased this one 👍

2024-09-19 18:09 UTC, vespos requested changes
Please fix the mapping and add the pre-release notes etc

2024-09-19 18:09 UTC, vespos commented on pcdsdevices/gon.py
> +    chi = Cpt(BeckhoffAxis, '2TH', kind='normal')
Fix variables names / PV suffix. th is mapping to CHI, etc

Let's call two_th - > tth instead

2024-09-30 16:23 UTC, vespos approved these changes
LGTM!

2024-09-30 20:59 UTC, ZLLentz requested changes
I think this still needs pre-release notes

2024-10-01 18:22 UTC, ZLLentz commented on docs/source/upcoming_release_notes/1274-Adding_base_class_for_hxr_diffractometer..rst
> +- N/A
You gotta credit yourself tho, you made the thing

2024-10-01 18:23 UTC, ZLLentz commented on docs/source/upcoming_release_notes/1274-Adding_base_class_for_hxr_diffractometer..rst
> +- N/A
Old template + wrong sorting
```suggestion
Library Features
--------
- N/A

Device Features
--------------
- N/A

New Devices
-----------
- Adding base class for hxr diffractometer, this class needs the base prefix to be passed in e.g. HXR:GON:MMS. The stage suffixes are hardcoded.
```

2024-10-01 18:24 UTC, ZLLentz commented on docs/source/upcoming_release_notes/1274-Adding_base_class_for_hxr_diffractometer..rst
> +- N/A
```suggestion
- c-tsoi
```

2024-10-01 18:25 UTC, ZLLentz approved these changes

2024-10-01 20:17 UTC, merged