REL: Release notes v8.5.0
pcdshub/pcdsdevices pull request #1277
Opened 2024-08-23 01:08 UTC by tangkong

## Description
- Compiles release notes
- modifies conda recipe to use bluesky-base, instead of matplotlib

## Motivation and Context
Note: conda-forge has a pint dependency that we don't have here.  We took this out https://github.com/pcdshub/pcdsdevices/pull/1253 

## How Has This Been Tested?
CI

## Where Has This Been Documented?
This PR, and this is docs

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive docstrings, including context and API
- [ ] New/changed functions and methods are covered in the test suite where possible
- [ ] Test suite passes locally
- [ ] Test suite passes on GitHub Actions
- [ ] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

2024-08-23 20:45 UTC, tangkong commented
I have requested reviews from all contributors to this tag, for the sake of spot checking our release notes.  Don't feel obligated to give a detailed review, but if you would like to refine any of the wording please leave a review!

2024-08-23 21:00 UTC, vespos approved these changes

2024-08-26 16:23 UTC, nrwslac approved these changes
lgtm!

2024-08-26 16:35 UTC, slactjohnson approved these changes

2024-08-26 16:37 UTC, baljamal submitted a review, later dismissed

2024-08-26 18:25 UTC, ZLLentz commented on pcdsdevices/_version.py
I think this was accidentally comitted

2024-08-26 18:30 UTC, ZLLentz commented on docs/source/releases.rst
> +- tongju12
Duplicate contributor name, tong is included below too (in alphabetical order)
```suggestion
```

2024-08-26 18:31 UTC, ZLLentz commented on docs/source/releases.rst
> +Features
I'm considering whether this should be changed from "Features" to "Library features" (new components, base classes, utils, etc.) to make it more clear that the device-specific features go in "Device Updates"

2024-08-26 18:39 UTC, ZLLentz requested changes
I'll put the request changes marker on because the _version.py file does break things
I'm happy to push a commit to rearrange releases.rst

2024-08-26 19:20 UTC, tangkong commented on pcdsdevices/_version.py
oh no

2024-08-26 21:14 UTC, ZLLentz approved these changes

2024-08-26 21:43 UTC, merged