Sl1k2 led
pcdshub/pcdsdevices pull request #723
Opened 2020-12-07 23:16 UTC by ghalym

Included meta data to the SL1K2-Exit Led control
## Description
Included meta data to the SL1K2-Exit Led control

## Motivation and Context
The LED has an analog control, with the meta data the user can control the output via a slide bar.

## How Has This Been Tested?
This has been tested from my local directory

## Where Has This Been Documented?

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive docstrings, including context and API
- [ ] New/changed functions and methods are covered in the test suite where possible
- [ ] Test suite passes locally
- [ ] Test suite passes on travis
- [ ] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

2020-12-07 23:19 UTC, klauer requested changes
Fix up the release notes, and this should be good-to-go. 👍

2020-12-07 23:19 UTC, klauer commented on docs/source/upcoming_release_notes/issue_number-update_ExitSlits.rst
> +- N/A
Please add a line here indicating the metadata addition

2020-12-07 23:19 UTC, klauer commented on docs/source/upcoming_release_notes/issue_number-update_ExitSlits.rst
> +- N/A
```suggestion
- ghalym
```

2020-12-08 00:25 UTC, klauer approved these changes
In the interest of getting this in your hands in the dev environment (Travis CI testing is so slow), I'll approve and merge. 

In the future, though, please make change log entries with full sentences that explain what has changed (for a human to understand).

2020-12-08 00:30 UTC, merged

2020-12-09 03:11 UTC, ZLLentz commented
I think I'll just end up deleting this line from the release notes anyway, because in the tag it is redundant with "added ExitSlits device"