Mirror sensor readouts
pcdshub/pcdsdevices pull request #949
Opened 2022-02-10 19:29 UTC by nrwslac

## Description
* Added cooling flow/pressure sensor readouts for KBO mirrors
* Added Y axis to device status output

## Motivation and Context
New hardware installed.

## How Has This Been Tested?
Ran in local pydev environment and view in a typhos screen with mirror mr2k4.

## Where Has This Been Documented?

## Screenshots:
<img width="692" alt="cool sensors" src="https://user-images.githubusercontent.com/79480290/153482241-43f8893f-db56-4871-92c5-54756bd6772a.png">

## Pre-merge checklist
- [ ] Code works interactively
- [ ] Code contains descriptive docstrings, including context and API
- [ ] New/changed functions and methods are covered in the test suite where possible
- [ ] Test suite passes locally
- [ ] Test suite passes on travis
- [ ] Ran docs/pre-release-notes.sh and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

2022-02-10 19:33 UTC, ZLLentz reviewed
I don't have much to say, this looks simple and clean. Happy to merge once the checklist is complete.

Also, TIL that `lpm` stands for "Liters per minute". Maybe a strange unit choice for the flow rates here? But that's unrelated to this PR.

2022-02-10 19:35 UTC, nrwslac commented
> I don't have much to say, this looks simple and clean. Happy to merge once the checklist is complete. Good job on the clear PR text too.
> 
> Also, TIL that `lpm` stands for "Liters per minute". Maybe a strange unit choice for the flow rates here? But that's unrelated to this PR.

correct, this unit was requested specifically.

2022-02-10 19:38 UTC, nrwslac commented
One concern is kbo mirrors using this class that do not have sensors installed will show PV discon here, but that seems okay.  All KBOs will receive these sensors from my understanding.

2022-02-10 21:54 UTC, nrwslac commented
> > One concern is kbo mirrors using this class that do not have sensors installed will show PV discon here, but that seems okay. All KBOs will receive these sensors from my understanding.
> 
> One way to alleviate this concern is to implement the additional sensors in a child class, and apply the new class in happi when the sensor PVs are added:
> 
> ```
> class CoolKBOMirror(KBOMirror):
>     # Cooling water flow and pressure sensors
>     cool_flow1  = Cpt(EpicsSignalRO, ':FLOW:1_RBV', kind='normal')
>     cool_flow2  = Cpt(EpicsSignalRO, ':FLOW:2_RBV', kind='normal')
>     cool_press = Cpt(EpicsSignalRO, ':PRESS:1_RBV', kind='normal')
> ```
> 
> (with a more normal class name, probably)

Personally I don't like using more inheritance than necessary; I prefer this method. But I am open to doing it in child class.

2022-02-10 21:55 UTC, ZryletTC requested changes
Looks good but yeah, these components should be added in a child class if some devices will have them and some will not.

2022-02-10 21:55 UTC, ZryletTC commented on pcdsdevices/mirror.py
> +    cool_flow2  = Cpt(EpicsSignalRO, ':FLOW:2_RBV', kind='normal')
```suggestion
    cool_flow1 = Cpt(EpicsSignalRO, ':FLOW:1_RBV', kind='normal')
    cool_flow2 = Cpt(EpicsSignalRO, ':FLOW:2_RBV', kind='normal')
```

2022-02-10 22:23 UTC, ZLLentz commented
I think it's correct to be inheritance-adverse. The thing to be wary of is complicated, deep inheritance trees. A small class that slightly extends a neighboring class in the same file isn't much of a concern I think.

The main hazards related to disconnected PVs in a screen are:
- Users seeing a disconnected PV and thinking something is broken, creating an extra support call
- There's a ... bug? in the positioners where a disconnected positioner PV is pretty fatal when requesting a move, but that doesn't apply here.

2022-02-11 20:07 UTC, nrwslac commented on pcdsdevices/mirror.py
> +    cool_flow2  = Cpt(EpicsSignalRO, ':FLOW:2_RBV', kind='normal')
fixed

2022-02-11 20:08 UTC, nrwslac commented
> I think it's correct to be inheritance-adverse. The thing to be wary of is complicated, deep inheritance trees. A small class that slightly extends a neighboring class in the same file isn't much of a concern I think.
> 
> The main hazards related to disconnected PVs in a screen are:
> 
> * Users seeing a disconnected PV and thinking something is broken, creating an extra support call
> * There's a ... bug? in the positioners where a disconnected positioner PV is pretty fatal when requesting a move, but that doesn't apply here.

Sounds like the benefits are outweighing the costs here. I updated to a child class.

2022-02-11 22:41 UTC, ZryletTC approved these changes
Looks good 👍

2022-02-11 22:41 UTC, ZryletTC commented on pcdsdevices/mirror.py
Needs two blank lines between classes.
```suggestion


class KBOMirrorHE(KBOMirror):
    """
    Kirkpatrick-Baez Mirror with Bender Axes and Cooling.

    1st gen Toyama designs with LCLS-II Beckhoff motion architecture.

    Parameters
    ----------
    prefix : str
        Base PV for the mirror.

    name : str
        Alias for the device.
    """
    # Cooling water flow and pressure sensors
    cool_flow1 = Cpt(EpicsSignalRO, ':FLOW:1_RBV', kind='normal')
    cool_flow2 = Cpt(EpicsSignalRO, ':FLOW:2_RBV', kind='normal')
    cool_press = Cpt(EpicsSignalRO, ':PRESS:1_RBV', kind='normal')


```

2022-02-11 23:24 UTC, nrwslac commented on pcdsdevices/mirror.py
fixed

2022-02-11 23:55 UTC, ZLLentz requested changes
Just needs the pre-release documentation as per the checklist.
```
cd docs
./pre-release-notes.sh 949 kbo-fixes
```

2022-02-12 02:52 UTC, ZryletTC commented on docs/source/upcoming_release_notes/949-kbo-fixes.rst
> +- N/A
```suggestion
- Added Y axis to KBOMirror status.

New Devices
-----------
- Added KBOMirrorHE class to be used with KBOMirrors with cooling, like MR2K4 KBO.
```

2022-02-12 02:52 UTC, ZryletTC commented on docs/source/upcoming_release_notes/949-kbo-fixes.rst
> +Nick Waters
```suggestion
- nrwslac
```

2022-02-14 17:45 UTC, nrwslac commented on docs/source/upcoming_release_notes/949-kbo-fixes.rst
> +Nick Waters
fixed

2022-02-14 18:37 UTC, ZLLentz approved these changes
Let's get it merged, lookin good!

2022-02-14 18:38 UTC, merged